theme = "nord"

[editor]
cursorline = true
shell = ["zsh"]
line-number = "absolute"
scrolloff = 10
bufferline = "multiple"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "version-control"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
skip-level = 1

[editor.file-picker]
hidden = false

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]


[keys.normal]
C-h = ":buffer-previous"
C-l = ":buffer-next"
C-w = ":buffer-close" 
