[[language]]
name = "latex"
language-servers = [ { name = "ltex-ls"}, {name = "texlab" , only-features = [ "completion" ] } ]
file-types = ["tex", "md"]
scope = "source.tex"
roots = ["Tectonic.toml"]
auto-format = true
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
text-width = 80
[languange-server.ltex-ls]
command = "/opt/homebrew/Cellar/ltex-ls/16.0.0/bin/ltex-ls"

[[language]]
name = "rust"
[language-server.rust-analyzer.config.check]
command = "clippy"
